---
title: "Deficit Habitacional"
author: "Diretoria do Monitoramento"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
    html_document:
       base_format: rticles::jss_article
       highlight: textmate
       theme: flatly
       number_sections: yes
       toc: yes
       toc_float:
         collapsed: yes
         smooth_scroll: no
---
# Déficit  Habitacional

O indicador busca calcular resultados para famílias em situação de déficit habitacional e/ou inadequação domiciliar, definidas mais especificamente como: a reposição de estoque, que contempla a necessidade de repor as habitações em função da sua precariedade e desgaste de uso. e o incremento de estoque, que refere-se a demanda por novas moradias decorente de: Coabitação forçada,ônus excessivo com aluguel e adensamento excessivo.

# Metodologia

O indicador Déficit Habitacional foi desenvolvido com base na metodologia definida na [Nota Técnica nº. 1 do IPEA Estimativas do déficit habitacional brasileiro (2007-2011) por municípios (2010)](https://www.ipea.gov.br/portal/images/stories/PDFs/nota_tecnica/130517_notatecnicadirur01.pdf), para o cálculo do déficit habitacional com dados do Censo 2010, que por sua vez, é baseada nos conceitos estabelecidos pela Fundação João Pinheiro (FJP) e o Ministério das Cidades.  
A base de dados utilizada foi a [PDAD 2018](http://www.codeplan.df.gov.br/microdados-pdad-2018/)(33 Ras), disponibilizada pela CODEPLAN.
entretanto, a metodologia proposta pela FJP se baseia no questionário da PNAD, mas como ambas pesquisas possuem as questões necessárias para o estudo, fez-se a equivalência entre suas questões.  
Note, que o indicador é composto por qualquer um de seus componentes ou subcomponentes, de modo que há domicílios nas quais mais de uma situação é observada, porém tal domicílio só é contado no total do déficit uma única vez. Em termos práticos, isso significa que a soma dos componentes é maior do que o valor do indicador do déficit habitacional.

## Precariedade

São consideradas habitações precárias todos aqueles domicílios que estejam classicados como **domícilios improvisados**. Outra categoria que também compõe as habitações precárias é a dos **domicílios Rústicos**, que são aqueles que embora sejam permanenetes não tenham alvenaria ou madeira aparelhada como material predominante nas paredes do domicílio.

## Coabitação

Contempla todas aquelas famílias que declaram viver em domicílios do tipo cômodo,independente da condição de sua ocupação (alugados,próprios ou cedidos), com isso tem-se o subcomponente **Famílias residentes em cômodos**. Há ainda o subcomponente **Famílias conviventes**, que ocorre quando há a presença de mais de um família residindo no mesmo domicílio e com intenção de mudar.

## Ônus excessivo com aluguel  

Caracteriza-se quando o peso pago com a prestação do aluguel no orçamento domiciliar for superior ou igual a 30% da renda domiciliar, sendo excluído do cálculo aquelas famílias cuja renda declarada é 0. Este indicador é calculado exclusivamente para os domicílios cujas rendas domiciliares são de até três salários mínimos. Segundo a metodologia desenvolvida pelo IPEA (2013), não é possível estabelecer que todos os domicílios que declaram a renda domiciliar igual a 0, apresentem-se estruturalmente sem renda (o que os impossibilitaria de fazer o pagamento do aluguel), ou se o fato é apenas conjuntural. Neste caso, optou-se por não incluir tais domicílios no cálculo do déficit.  

## Adensamento excessivo

Ocorre em domicílios alugados, que possuem mais de três habitantes por cômodo utilizado, permanentemente, como dormitório. 

# Resultados






```{r Pacotes, message=FALSE, warning=FALSE, echo=FALSE}
library(plotly)
library(tidyverse)
library(survey)
library(srvyr)
library(sidrar)
library(readr)
library(dplyr)                                
library(ggplot2)
library(knitr)
library(kableExtra)
library(htmltools)
```




